### ISSUE TITLE
The package is missing a LICENSE file and therefore running into security complains in Nexus

### ISSUE THREAD

**Issue by awacode21** [jmar777/cb#12]
The package is missing a LICENSE file and therefore running into security complains in Nexus. As this package is a dependency of another package we use, it prevents our production build from succeeding because of missing license file. Please add license.

**Comment by jmar777** [comment]
Hey - working to get one added now. Running into an error while attempting to publish, but I hope to resolve it soon.

**Comment by jmar777** [comment]
Alright, a LICENSE file (MIT) has been published with v0.1.1. Thanks for filing an issue!

**Comment by awacode21** [comment]
Thanks for the quick response and solution
